server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/imageuploader?useSSL=false&serverTimezone=UTC
    username: root
    password: 0d000721
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
jwt:
  secret: muzixiao2-jwt-sign-key-1234567890-xx
  expiration: 86400